# Simple workflow for deploying static content to GitHub Pages
name: Deploy to cPanel

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
#   group: "pages"
#   cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    #pull repo code to the VM
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #upload files to your cPanel server via FTP
      - name: deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./               # Root of your repo
          server-dir: /public_html/
          protocol: ftp
          port: 21

      # - name: deploy via SFTP
      #   uses: burnett01/rsync-deployments@7.0.1
      #   with:
      #     switches: -avzr --delete
      #     path: ./
      #     remote_path: /public_html/
      #     remote_host: ${{ secrets.FTP_HOST }}
      #     remote_user: ${{ secrets.FTP_USER }}
      #     remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
